
url: https://joycewufm.github.io/
baseurl: ""

# Site settings
title: Joyce wanna go big
email: joycewufm@gmail.com
#---------------------------need to change!!!
description: "Have no idea yet, but someday will be seem."
#---------------------------need to change!!!

#---------------------------need to change!!!
# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
#---------------------------need to change!!!

#---------------------------need to change!!!
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/JoyceWufm

# Postal address (add as many lines as necessary)
address:
  - line: --
  - line: --
#---------------------------need to change!!!

# Build settings
markdown: kramdown
permalink: pretty

port: 8888